/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Statsig example project
 * Environment: Production
 * Id: 24f53ed7-b7e6-010a-591a-fdf83b5013c3
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { StatsigExperimentType } from '../types/statsig-experiment-type.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Article Page' type
*/
            export type ArticlePageTypeCodename = keyof Pick<Record<TypeCodenames, null>, "article_page">;

            /*
* Typeguard for codename of 'Article Page' type
*/
            export function isArticlePageTypeCodename(value: string | undefined | null): value is ArticlePageTypeCodename {
                return typeof value === 'string' && value === ('article_page' satisfies ArticlePageTypeCodename);
            }

/*
    * Article Page
    *
    * Id: 21505781-7bc2-4083-bcda-1c8683edc2ec
* Codename: article_page
    */
export type ArticlePageType = IContentItem<
{
/*
    * Title
    *
    * Codename: title
* Id: b53cc60e-d01d-4408-8c2d-b1df85c9e3f3
* Type: text
* Required: true
* Guidelines: The title of the article.
    */
                readonly title: Elements.TextElement;

/*
    * Body
    *
    * Codename: body
* Id: 620d8e69-3993-40ac-93a3-ec83bff741c0
* Type: rich_text
* Required: false
* Allowed content types: statsig_experiment
* Guidelines: The main body content. You can embed Statsig experiments as components.
    */
                readonly body: Elements.RichTextElement<StatsigExperimentType>;}, 
ArticlePageTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Article Page
*/
export type ArticlePageTypeElementCodenames = 'title' | 'body';;

/*
    * Type guard for Article Page
    *
    * Id: 21505781-7bc2-4083-bcda-1c8683edc2ec
* Codename: article_page
    */
export function isArticlePageType(item: IContentItem | undefined | null): item is ArticlePageType {
                return item?.system.type === ('article_page' satisfies ArticlePageTypeCodename);
            };



            