/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Statsig test
 * Environment: Production
 * Id: 4b3df685-f22d-0149-c469-58e77da389ec
 *
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk";
import type { CollectionCodenames } from "../system/collections.generated.js";
import type { LanguageCodenames } from "../system/languages.generated.js";
import type { TypeCodenames } from "../system/types.generated.js";
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated.js";
import type { StatsigExperimentType } from "../types/statsig-experiment-type.generated.js";

/*
 * Type representing codename of 'Article Page' type
 */
export type ArticlePageTypeCodename = keyof Pick<Record<TypeCodenames, null>, "article_page">;

/*
 * Typeguard for codename of 'Article Page' type
 */
export function isArticlePageTypeCodename(
  value: string | undefined | null,
): value is ArticlePageTypeCodename {
  return typeof value === "string" && value === ("article_page" satisfies ArticlePageTypeCodename);
}

/*
 * Article Page
 *
 * Id: 0b44ae96-8910-468e-aa1f-bccadf150efa
 * Codename: article_page
 */
export type ArticlePageType = IContentItem<
  {
    /*
     * Title
     *
     * Codename: title
     * Id: 4e5042a2-16e8-426a-8ebd-712ae670c842
     * Type: text
     * Required: true
     * Guidelines: The title of the article.
     */
    readonly title: Elements.TextElement;

    /*
     * Body
     *
     * Codename: body
     * Id: 900f4766-4a14-4d70-a55d-2241da375101
     * Type: rich_text
     * Required: false
     * Allowed content types: statsig_experiment
     * Guidelines: The main body content. You can embed Statsig experiments as components.
     */
    readonly body: Elements.RichTextElement<StatsigExperimentType>;
  },
  ArticlePageTypeCodename,
  LanguageCodenames,
  CollectionCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames
>;

/*
 * Type representing all available element codenames for Article Page
 */
export type ArticlePageTypeElementCodenames = "title" | "body";

/*
 * Type guard for Article Page
 *
 * Id: 0b44ae96-8910-468e-aa1f-bccadf150efa
 * Codename: article_page
 */
export function isArticlePageType(item: IContentItem | undefined | null): item is ArticlePageType {
  return item?.system.type === ("article_page" satisfies ArticlePageTypeCodename);
}
