/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Statsig test
 * Environment: Production
 * Id: 4b3df685-f22d-0149-c469-58e77da389ec
 *
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk";
import type { CollectionCodenames } from "../system/collections.generated.js";
import type { LanguageCodenames } from "../system/languages.generated.js";
import type { TypeCodenames } from "../system/types.generated.js";
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated.js";
import type { StatsigExperimentType } from "../types/statsig-experiment-type.generated.js";

/*
 * Type representing codename of 'Landing Page' type
 */
export type LandingPageTypeCodename = keyof Pick<Record<TypeCodenames, null>, "landing_page">;

/*
 * Typeguard for codename of 'Landing Page' type
 */
export function isLandingPageTypeCodename(
  value: string | undefined | null,
): value is LandingPageTypeCodename {
  return typeof value === "string" && value === ("landing_page" satisfies LandingPageTypeCodename);
}

/*
 * Landing Page
 *
 * Id: 13727457-eb47-4cc6-a46a-9adca3ebec47
 * Codename: landing_page
 */
export type LandingPageType = IContentItem<
  {
    /*
     * Title
     *
     * Codename: title
     * Id: f6f7170a-9e6f-48d8-94b7-63c775781c61
     * Type: text
     * Required: true
     * Guidelines: The title of the landing page.
     */
    readonly title: Elements.TextElement;

    /*
     * Experiments
     *
     * Codename: experiments
     * Id: e088ed10-5f96-42b2-8779-be6bc6c4dbc1
     * Type: modular_content
     * Required: false
     * Allowed content types: statsig_experiment
     * Guidelines: Experiments to run on this page. Each experiment links to a Statsig experiment and contains control/test content variants.
     */
    readonly experiments: Elements.LinkedItemsElement<StatsigExperimentType>;
  },
  LandingPageTypeCodename,
  LanguageCodenames,
  CollectionCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames
>;

/*
 * Type representing all available element codenames for Landing Page
 */
export type LandingPageTypeElementCodenames = "title" | "experiments";

/*
 * Type guard for Landing Page
 *
 * Id: 13727457-eb47-4cc6-a46a-9adca3ebec47
 * Codename: landing_page
 */
export function isLandingPageType(item: IContentItem | undefined | null): item is LandingPageType {
  return item?.system.type === ("landing_page" satisfies LandingPageTypeCodename);
}
