/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Statsig example project
 * Environment: Production
 * Id: 24f53ed7-b7e6-010a-591a-fdf83b5013c3
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { StatsigExperimentType } from '../types/statsig-experiment-type.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Landing Page' type
*/
            export type LandingPageTypeCodename = keyof Pick<Record<TypeCodenames, null>, "landing_page">;

            /*
* Typeguard for codename of 'Landing Page' type
*/
            export function isLandingPageTypeCodename(value: string | undefined | null): value is LandingPageTypeCodename {
                return typeof value === 'string' && value === ('landing_page' satisfies LandingPageTypeCodename);
            }

/*
    * Landing Page
    *
    * Id: 40995df5-b728-4ea6-beaf-5f77c8035633
* Codename: landing_page
    */
export type LandingPageType = IContentItem<
{
/*
    * Title
    *
    * Codename: title
* Id: 99051af8-79d1-4cfe-8553-c65988cf89d9
* Type: text
* Required: true
* Guidelines: The title of the landing page.
    */
                readonly title: Elements.TextElement;

/*
    * Experiments
    *
    * Codename: experiments
* Id: a4d83e29-00ab-48cc-a59a-0c1d2011725b
* Type: modular_content
* Required: false
* Allowed content types: statsig_experiment
* Guidelines: Experiments to run on this page. Each experiment links to a Statsig experiment and contains control/test content variants.
    */
                readonly experiments: Elements.LinkedItemsElement<StatsigExperimentType>;}, 
LandingPageTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Landing Page
*/
export type LandingPageTypeElementCodenames = 'title' | 'experiments';;

/*
    * Type guard for Landing Page
    *
    * Id: 40995df5-b728-4ea6-beaf-5f77c8035633
* Codename: landing_page
    */
export function isLandingPageType(item: IContentItem | undefined | null): item is LandingPageType {
                return item?.system.type === ('landing_page' satisfies LandingPageTypeCodename);
            };



            