/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Statsig example project
 * Environment: Production
 * Id: 24f53ed7-b7e6-010a-591a-fdf83b5013c3
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Text Block' type
*/
            export type TextBlockTypeCodename = keyof Pick<Record<TypeCodenames, null>, "text_block">;

            /*
* Typeguard for codename of 'Text Block' type
*/
            export function isTextBlockTypeCodename(value: string | undefined | null): value is TextBlockTypeCodename {
                return typeof value === 'string' && value === ('text_block' satisfies TextBlockTypeCodename);
            }

/*
    * Text Block
    *
    * Id: b8176303-8fa7-41aa-b48e-f813e22b5dd0
* Codename: text_block
    */
export type TextBlockType = IContentItem<
{
/*
    * Text
    *
    * Codename: text
* Id: b2326c0b-0e49-477f-93bf-623df099bdcb
* Type: text
* Required: true
* Guidelines: The text content of this block.
    */
                readonly text: Elements.TextElement;}, 
TextBlockTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Text Block
*/
export type TextBlockTypeElementCodenames = 'text';;

/*
    * Type guard for Text Block
    *
    * Id: b8176303-8fa7-41aa-b48e-f813e22b5dd0
* Codename: text_block
    */
export function isTextBlockType(item: IContentItem | undefined | null): item is TextBlockType {
                return item?.system.type === ('text_block' satisfies TextBlockTypeCodename);
            };



            