/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Statsig test
 * Environment: Production
 * Id: 4b3df685-f22d-0149-c469-58e77da389ec
 *
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk";
import type { CollectionCodenames } from "../system/collections.generated.js";
import type { LanguageCodenames } from "../system/languages.generated.js";
import type { TypeCodenames } from "../system/types.generated.js";
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated.js";

/*
 * Type representing codename of 'Text Block' type
 */
export type TextBlockTypeCodename = keyof Pick<Record<TypeCodenames, null>, "text_block">;

/*
 * Typeguard for codename of 'Text Block' type
 */
export function isTextBlockTypeCodename(
  value: string | undefined | null,
): value is TextBlockTypeCodename {
  return typeof value === "string" && value === ("text_block" satisfies TextBlockTypeCodename);
}

/*
 * Text Block
 *
 * Id: d4a1d6bd-b8e7-44e7-95b4-5ccd35a4fe75
 * Codename: text_block
 */
export type TextBlockType = IContentItem<
  {
    /*
     * Text
     *
     * Codename: text
     * Id: 9e2cda09-7ae1-4137-b1f2-2bff6baa0018
     * Type: text
     * Required: true
     * Guidelines: The text content of this block.
     */
    readonly text: Elements.TextElement;
  },
  TextBlockTypeCodename,
  LanguageCodenames,
  CollectionCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames
>;

/*
 * Type representing all available element codenames for Text Block
 */
export type TextBlockTypeElementCodenames = "text";

/*
 * Type guard for Text Block
 *
 * Id: d4a1d6bd-b8e7-44e7-95b4-5ccd35a4fe75
 * Codename: text_block
 */
export function isTextBlockType(item: IContentItem | undefined | null): item is TextBlockType {
  return item?.system.type === ("text_block" satisfies TextBlockTypeCodename);
}
