/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Statsig test
 * Environment: Production
 * Id: 4b3df685-f22d-0149-c469-58e77da389ec
 * 
 * -------------------------------------------------------------------------------
 */


            import type { CollectionCodenames } from '../system/collections.generated.js';
           
            /*
* Type representing codename of 'Default' collection
*/
            export type DefaultCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "default">;

            /*
* Typeguard for codename of 'Default' collection
*/
            export function isDefaultCollectionCodename(value: string | undefined | null): value is DefaultCollectionCodename {
                return typeof value === 'string' && value === ('default' satisfies DefaultCollectionCodename);
            }
            