/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Statsig test
 * Environment: Production
 * Id: 4b3df685-f22d-0149-c469-58e77da389ec
 * 
 * -------------------------------------------------------------------------------
 */


            import type { LanguageCodenames } from '../system/languages.generated.js';
           
            /*
* Type representing codename of 'Default project language' language
*/
            export type DefaultProjectLanguageLanguageCodename = keyof Pick<Record<LanguageCodenames, null>, "default">;

            /*
* Typeguard for codename of 'Default project language' language
*/
            export function isDefaultProjectLanguageLanguageCodename(value: string | undefined | null): value is DefaultProjectLanguageLanguageCodename {
                return typeof value === 'string' && value === ('default' satisfies DefaultProjectLanguageLanguageCodename);
            }
            