/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Statsig example project
 * Environment: Production
 * Id: 24f53ed7-b7e6-010a-591a-fdf83b5013c3
 * 
 * -------------------------------------------------------------------------------
 */


            
            /*
* Array of all collection codenames
*/
            export const collectionCodenames = ['default'] as const;;
           
            /*
* Type representing all collection codenames
*/
            export type CollectionCodenames = typeof collectionCodenames[number];;

            /*
* Typeguard for collection codename
*/
            export function isCollectionCodename(value: string | undefined | null): value is CollectionCodenames {
                return typeof value === 'string' && (collectionCodenames as readonly string[]).includes(value);
            };