/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Statsig test
 * Environment: Production
 * Id: 4b3df685-f22d-0149-c469-58e77da389ec
 *
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all collection codenames
 */
export const collectionCodenames = ["default"] as const;

/*
 * Type representing all collection codenames
 */
export type CollectionCodenames = (typeof collectionCodenames)[number];

/*
 * Typeguard for collection codename
 */
export function isCollectionCodename(
  value: string | undefined | null,
): value is CollectionCodenames {
  return typeof value === "string" && (collectionCodenames as readonly string[]).includes(value);
}
