/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Statsig example project
 * Environment: Production
 * Id: 24f53ed7-b7e6-010a-591a-fdf83b5013c3
 * 
 * -------------------------------------------------------------------------------
 */


            
            /*
* Array of all element codenames
*/
            export const elementCodenames = ['text', 'statsig_a_b_testing', 'control', 'test', 'title', 'experiments', 'body'] as const;;
           
            /*
* Type representing all element codenames
*/
            export type ElementCodenames = typeof elementCodenames[number];;

            /*
* Typeguard for element codename
*/
            export function isElementCodename(value: string | undefined | null): value is ElementCodenames {
                return typeof value === 'string' && (elementCodenames as readonly string[]).includes(value);
            };