/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Statsig example project
 * Environment: Production
 * Id: 24f53ed7-b7e6-010a-591a-fdf83b5013c3
 * 
 * -------------------------------------------------------------------------------
 */


            
            /*
* Array of all language codenames
*/
            export const languageCodenames = ['default'] as const;;
           
            /*
* Type representing all language codenames
*/
            export type LanguageCodenames = typeof languageCodenames[number];;

            /*
* Typeguard for language codename
*/
            export function isLanguageCodename(value: string | undefined | null): value is LanguageCodenames {
                return typeof value === 'string' && (languageCodenames as readonly string[]).includes(value);
            };