/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Statsig test
 * Environment: Production
 * Id: 4b3df685-f22d-0149-c469-58e77da389ec
 * 
 * -------------------------------------------------------------------------------
 */


            
            /*
* Array of all language codenames
*/
            export const languageCodenames = ['default'] as const;;
           
            /*
* Type representing all language codenames
*/
            export type LanguageCodenames = typeof languageCodenames[number];;

            /*
* Typeguard for language codename
*/
            export function isLanguageCodename(value: string | undefined | null): value is LanguageCodenames {
                return typeof value === 'string' && (languageCodenames as readonly string[]).includes(value);
            };