/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Statsig test
 * Environment: Production
 * Id: 4b3df685-f22d-0149-c469-58e77da389ec
 *
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all snippet codenames
 */
export const snippetCodenames = [] as const;

/*
 * Type representing all snippet codenames
 */
export type SnippetCodenames = (typeof snippetCodenames)[number];

/*
 * Typeguard for snippet codename
 */
export function isSnippetCodename(value: string | undefined | null): value is SnippetCodenames {
  return typeof value === "string" && (snippetCodenames as readonly string[]).includes(value);
}
