/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Statsig example project
 * Environment: Production
 * Id: 24f53ed7-b7e6-010a-591a-fdf83b5013c3
 * 
 * -------------------------------------------------------------------------------
 */


            
            /*
* Array of all taxonomy codenames
*/
            export const taxonomyCodenames = [] as const;;
           
            /*
* Type representing all taxonomy codenames
*/
            export type TaxonomyCodenames = typeof taxonomyCodenames[number];;

            /*
* Typeguard for taxonomy codename
*/
            export function isTaxonomyCodename(value: string | undefined | null): value is TaxonomyCodenames {
                return typeof value === 'string' && (taxonomyCodenames as readonly string[]).includes(value);
            };