/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Statsig test
 * Environment: Production
 * Id: 4b3df685-f22d-0149-c469-58e77da389ec
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TextBlockType } from '../types/text-block-type.generated.js';
import type { StatsigExperimentType } from '../types/statsig-experiment-type.generated.js';
import type { LandingPageType } from '../types/landing-page-type.generated.js';
import type { ArticlePageType } from '../types/article-page-type.generated.js';

            /*
* Array of all type codenames
*/
            export const typeCodenames = ['text_block', 'statsig_experiment', 'landing_page', 'article_page'] as const;;
           
            /*
* Type representing all type codenames
*/
            export type TypeCodenames = typeof typeCodenames[number];;

            /*
* Typeguard for type codename
*/
            export function isTypeCodename(value: string | undefined | null): value is TypeCodenames {
                return typeof value === 'string' && (typeCodenames as readonly string[]).includes(value);
            };

					 /*
* Core content type with narrowed types. Use this instead of'IContentItem' for increased type safety.
*/
					 export type CoreType = TextBlockType | StatsigExperimentType | LandingPageType | ArticlePageType

					/*
* Type mapping for codename & type. Can be used for type safe access to type based on the codename of type.
*/
					export type CodenameTypeMapping = {
	readonly text_block: TextBlockType,
readonly statsig_experiment: StatsigExperimentType,
readonly landing_page: LandingPageType,
readonly article_page: ArticlePageType,
};

					/*
* Helper type that returns type based on the codename of type.
*/
					export type CodenameTypeMapper<TTypeCodename extends TypeCodenames> = TTypeCodename extends keyof CodenameTypeMapping ? CodenameTypeMapping[TTypeCodename] : CoreType;
					