/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Statsig test
 * Environment: Production
 * Id: 4b3df685-f22d-0149-c469-58e77da389ec
 *
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all workflow codenames
 */
export const workflowCodenames = ["default"] as const;

/*
 * Type representing all workflow codenames
 */
export type WorkflowCodenames = (typeof workflowCodenames)[number];

/*
 * Typeguard for workflow codename
 */
export function isWorkflowCodename(value: string | undefined | null): value is WorkflowCodenames {
  return typeof value === "string" && (workflowCodenames as readonly string[]).includes(value);
}

/*
 * Array of all workflow codenames
 */
export const workflowStepCodenames = ["draft", "published", "archived", "scheduled"] as const;

/*
 * Type representing all workflow codenames
 */
export type WorkflowStepCodenames = (typeof workflowStepCodenames)[number];

/*
 * Typeguard for workflow codename
 */
export function isWorkflowStepCodename(
  value: string | undefined | null,
): value is WorkflowStepCodenames {
  return typeof value === "string" && (workflowStepCodenames as readonly string[]).includes(value);
}
